### ISSUE TITLE
Commander ability-power accrual

### ISSUE THREAD

**Issue by ThatIsAUsername** [ThislsAUsername/DefendPeace#103]
Commanders currently don't have a way to build power to use abilities. Fix this.

**Comment by ThislsAUsername** [comment]
I believe we had some discussions about this before, but didn't entirely come to a consensus.
I was in favor of HP-based power growth (gained by attacking only), as that's the approach DoR uses and nicely discourages infantry spam. Then again, we could use other methods to make infantry walls less appealing.
I don't think the Dual Strike approach of assigning each unit an accrual value; it should be directly tied to funds cost or HP, I think.
Either way, I think I would like faster charging powers than AW2.

**Comment by ThatIsAUsername** [comment]
I did sort of like having more power growth when on the losing end of things, and intuitively it makes more sense to scale it based on unit cost rather than HP, but I understand the arguments for other approaches as well (prevent stalemates, discourage inf spam), so I can go either way. We could even go crazy and let individual COs override whatever default setting we use (e.g., Commander Bloodlust gets +500% from doing damage, and/or LOSES power when being damaged, or something silly like that).

I'm frankly not too hung up on what exactly we do, so if you have a vision, I'd say go for it.

**Comment by ThislsAUsername** [comment]
I definitely like the idea of configurable power growth. I think probably Commander would just have a basic overrideable function that units call whenever they get hurt?
If we wanted COs to be able to accumulate power by doing things other than combat, though, it might get more complicated.

Regardless, I don't have any particular vision. It might be worth it to just do a dual approach (something like 10HP is half a star, and you also gain charge based on money)
Do we want power costs to increase with each cast?

**Comment by ThatIsAUsername** [comment]
I was half-joking with configurable power growth... I assume in practice, we'd just change how much power (not stars!) the Commander needs for an ability, unless we wanted to get creative and do negatives or whatever. I mean, we can if we can think of a decent use for it I guess, but I feel like it would add complexity, and wouldn't actually get used much.

I think there's some sense to increasing power cost after each cast, but we'd have to sort out how exactly that works. Does it increase cost for all abilities, or just the one that was cast the first time? Does in increase differently based on which ability is cast? Especially since we are considering allowing Commanders to have more than two abilities.

This issue isn't about ability cost though, just power accrual.

**Comment by ThislsAUsername** [comment]
Following on a discussion I just had with some other folks, at some point I definitely want a game mode with a configurable power meter income every turn. Could give a lot of variety to gameplay with not much development effort!

**Comment by ThislsAUsername** [comment]
I guess my vote would be for power cost increasing only for the power that was used. Dual Strike similarly only scales costs for a CO that *uses* a power, so if you have an Adder/Eagle tag, Eagle is gonna keep charging at full speed until he actually uses a power, while Adder will slow down.

The increase amount is fixed in AW, and I don't see a need to change that. I don't think DoR's powers scaled in cost at all, so that's just as viable an example.

I think it might be interesting to let individual powers determine how their cost scales, or if there's unified scaling, how they individually change the cost.

**Comment by ThatIsAUsername** [comment]
I'm open to gratis power per-turn as a game option; that could be interesting for sure.

I was going to go add graphics for the power meter, and realized the current CO ability infrastructure is mostly still imaginary at this point, so I ended up implementing abilities for Strong and Patch instead (and re-wickering some things in the process).

They still don't have a way to actually _gain_ power yet, but they can activate abilities now. I'm still working on it, but I pushed up the 'abilities' branch with what I've done so far.

**Comment by ThislsAUsername** [comment]
Proposal:
AW2-style power gain (9k/"star", half benefit for attacking), but with 150 funds credit for each HP you destroy.
This puts infantry at a 2k credit for the attacker, but only 1k for the defender... but more expensive units tilt that back the other way.
Thoughts?

**Comment by ThislsAUsername** [comment]
Solved by #111 
Ancillary concern moved to  #118
